
import javax.swing.*;
import java.awt.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class HomeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeJFrame
     */
    public HomeJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePane = new javax.swing.JPanel();
        inventoryBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        saleBtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        categoryBtn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        supplierBtn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        productBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        customerBtn = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        paymentBtn = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        saleBtn1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        productBtn1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        categoryBtn1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        customerBtn1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        supplierBtn1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        userBtn1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        inventoryBtn1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 728));
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1366, 728));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePane.setBackground(new java.awt.Color(54, 33, 89));
        sidePane.setPreferredSize(new java.awt.Dimension(250, 728));
        sidePane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sidePaneMouseDragged(evt);
            }
        });
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventoryBtn.setBackground(new java.awt.Color(64, 43, 100));
        inventoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryBtnMouseExited(evt);
            }
        });
        inventoryBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_in_inventory_15px.png"))); // NOI18N
        inventoryBtn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 42));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Product Inventory");
        inventoryBtn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 11, 134, -1));

        sidePane.add(inventoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 250, -1));

        saleBtn.setBackground(new java.awt.Color(64, 43, 100));
        saleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saleBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saleBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saleBtnMouseExited(evt);
            }
        });
        saleBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_land_sales_filled_15px.png"))); // NOI18N
        saleBtn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 42));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Sales");
        saleBtn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 11, 134, -1));

        sidePane.add(saleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, -1));

        dashboardBtn.setBackground(new java.awt.Color(85, 85, 118));
        dashboardBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_dashboard_15px.png"))); // NOI18N
        dashboardBtn.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 42));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Dashboard");
        dashboardBtn.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 11, 134, -1));

        sidePane.add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, -1));

        categoryBtn.setBackground(new java.awt.Color(64, 43, 100));
        categoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categoryBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                categoryBtnMouseExited(evt);
            }
        });
        categoryBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_dashboard_15px_1.png"))); // NOI18N
        categoryBtn.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 42));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Category");
        categoryBtn.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 11, 134, -1));

        sidePane.add(categoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, -1));

        supplierBtn.setBackground(new java.awt.Color(64, 43, 100));
        supplierBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplierBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplierBtnMouseExited(evt);
            }
        });
        supplierBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_supplier_15px.png"))); // NOI18N
        supplierBtn.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 42));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Suppliers");
        supplierBtn.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 11, 134, -1));

        sidePane.add(supplierBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 250, -1));

        productBtn.setBackground(new java.awt.Color(64, 43, 100));
        productBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productBtnMouseExited(evt);
            }
        });
        productBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_box_15px_1.png"))); // NOI18N
        productBtn.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 42));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Products");
        productBtn.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 11, 134, -1));

        sidePane.add(productBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, -1));

        customerBtn.setBackground(new java.awt.Color(64, 43, 100));
        customerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customerBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customerBtnMouseExited(evt);
            }
        });
        customerBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_crowd_filled_15px.png"))); // NOI18N
        customerBtn.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 42));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Customers");
        customerBtn.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 11, 134, -1));

        sidePane.add(customerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Retail Management");
        sidePane.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        sidePane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 220, 10));

        paymentBtn.setBackground(new java.awt.Color(64, 43, 100));
        paymentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paymentBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paymentBtnMouseExited(evt);
            }
        });
        paymentBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_in_inventory_15px.png"))); // NOI18N
        paymentBtn.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 42));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("Payment");
        paymentBtn.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 11, 134, -1));

        sidePane.add(paymentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 250, -1));

        bg.add(sidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        jPanel1.setBackground(new java.awt.Color(122, 72, 221));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Dashboard");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_dashboard_36px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addContainerGap(897, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 1180, 100));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_close_window_25px.png"))); // NOI18N
        closeBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeBtnMousePressed(evt);
            }
        });
        bg.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 0, 60, 30));

        saleBtn1.setBackground(new java.awt.Color(64, 43, 100));
        saleBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saleBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saleBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saleBtn1MouseExited(evt);
            }
        });

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_land_sales_filled_15px.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Sales");

        javax.swing.GroupLayout saleBtn1Layout = new javax.swing.GroupLayout(saleBtn1);
        saleBtn1.setLayout(saleBtn1Layout);
        saleBtn1Layout.setHorizontalGroup(
            saleBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        saleBtn1Layout.setVerticalGroup(
            saleBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saleBtn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap())
        );

        bg.add(saleBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 190, 80));

        productBtn1.setBackground(new java.awt.Color(64, 43, 100));
        productBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productBtn1MouseExited(evt);
            }
        });

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_box_15px_1.png"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Products");

        javax.swing.GroupLayout productBtn1Layout = new javax.swing.GroupLayout(productBtn1);
        productBtn1.setLayout(productBtn1Layout);
        productBtn1Layout.setHorizontalGroup(
            productBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        productBtn1Layout.setVerticalGroup(
            productBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productBtn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addContainerGap())
        );

        bg.add(productBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 190, 80));

        categoryBtn1.setBackground(new java.awt.Color(64, 43, 100));
        categoryBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categoryBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                categoryBtn1MouseExited(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_dashboard_15px_1.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Categories");

        javax.swing.GroupLayout categoryBtn1Layout = new javax.swing.GroupLayout(categoryBtn1);
        categoryBtn1.setLayout(categoryBtn1Layout);
        categoryBtn1Layout.setHorizontalGroup(
            categoryBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        categoryBtn1Layout.setVerticalGroup(
            categoryBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categoryBtn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        bg.add(categoryBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 280, 190, 80));

        customerBtn1.setBackground(new java.awt.Color(64, 43, 100));
        customerBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customerBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customerBtn1MouseExited(evt);
            }
        });

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_crowd_filled_15px.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Customers");

        javax.swing.GroupLayout customerBtn1Layout = new javax.swing.GroupLayout(customerBtn1);
        customerBtn1.setLayout(customerBtn1Layout);
        customerBtn1Layout.setHorizontalGroup(
            customerBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        customerBtn1Layout.setVerticalGroup(
            customerBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerBtn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addContainerGap())
        );

        bg.add(customerBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        supplierBtn1.setBackground(new java.awt.Color(64, 43, 100));
        supplierBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplierBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplierBtn1MouseExited(evt);
            }
        });

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_supplier_15px.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Suppliers");

        javax.swing.GroupLayout supplierBtn1Layout = new javax.swing.GroupLayout(supplierBtn1);
        supplierBtn1.setLayout(supplierBtn1Layout);
        supplierBtn1Layout.setHorizontalGroup(
            supplierBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        supplierBtn1Layout.setVerticalGroup(
            supplierBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, supplierBtn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addContainerGap())
        );

        bg.add(supplierBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, -1, -1));

        userBtn1.setBackground(new java.awt.Color(64, 43, 100));
        userBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userBtn1MouseExited(evt);
            }
        });

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_user_shield_15px.png"))); // NOI18N

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("User Manager");

        javax.swing.GroupLayout userBtn1Layout = new javax.swing.GroupLayout(userBtn1);
        userBtn1.setLayout(userBtn1Layout);
        userBtn1Layout.setHorizontalGroup(
            userBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        userBtn1Layout.setVerticalGroup(
            userBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userBtn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addContainerGap())
        );

        bg.add(userBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 380, -1, -1));

        inventoryBtn1.setBackground(new java.awt.Color(64, 43, 100));
        inventoryBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryBtn1MouseExited(evt);
            }
        });

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_in_inventory_15px.png"))); // NOI18N

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 204, 204));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Product Inventory");

        javax.swing.GroupLayout inventoryBtn1Layout = new javax.swing.GroupLayout(inventoryBtn1);
        inventoryBtn1.setLayout(inventoryBtn1Layout);
        inventoryBtn1Layout.setHorizontalGroup(
            inventoryBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        inventoryBtn1Layout.setVerticalGroup(
            inventoryBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventoryBtn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addContainerGap())
        );

        bg.add(inventoryBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sidePaneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePaneMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_sidePaneMouseDragged

    private void closeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseEntered
        // TODO add your handling code here:
        closeBtn.setIcon(new ImageIcon("E:\\UVA\\RetailApplication\\src\\image\\icons8_close_window_25px_1.png"));
        
    }//GEN-LAST:event_closeBtnMouseEntered

    private void closeBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_closeBtnMousePressed

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeBtnMouseClicked

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        // TODO add your handling code here:
        closeBtn.setIcon(new ImageIcon("E:\\UVA\\RetailApplication\\src\\image\\icons8_close_window_25px.png"));
    }//GEN-LAST:event_closeBtnMouseExited

    private void categoryBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryBtnMouseEntered
        // TODO add your handling code here:
        setBackgroundBtn(categoryBtn);
    }//GEN-LAST:event_categoryBtnMouseEntered

    private void categoryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryBtnMouseExited
        // TODO add your handling code here:
        resetBackgroundBtn(categoryBtn);
    }//GEN-LAST:event_categoryBtnMouseExited

    private void supplierBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierBtnMouseEntered
        // TODO add your handling code here:
        setBackgroundBtn(supplierBtn);
    }//GEN-LAST:event_supplierBtnMouseEntered

    private void supplierBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierBtnMouseExited
        // TODO add your handling code here:
        resetBackgroundBtn(supplierBtn);
    }//GEN-LAST:event_supplierBtnMouseExited

    private void productBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productBtnMouseEntered
        // TODO add your handling code here:
        setBackgroundBtn(productBtn);
    }//GEN-LAST:event_productBtnMouseEntered

    private void productBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productBtnMouseExited
        // TODO add your handling code here:
        resetBackgroundBtn(productBtn);
    }//GEN-LAST:event_productBtnMouseExited

    private void customerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerBtnMouseEntered
        // TODO add your handling code here:
        setBackgroundBtn(customerBtn);
    }//GEN-LAST:event_customerBtnMouseEntered

    private void customerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerBtnMouseExited
        // TODO add your handling code here:
        resetBackgroundBtn(customerBtn);
    }//GEN-LAST:event_customerBtnMouseExited

    private void saleBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleBtnMouseEntered
        // TODO add your handling code here:
        setBackgroundBtn(saleBtn);
    }//GEN-LAST:event_saleBtnMouseEntered

    private void saleBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleBtnMouseExited
        // TODO add your handling code here:
        resetBackgroundBtn(saleBtn);
    }//GEN-LAST:event_saleBtnMouseExited

    private void inventoryBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtnMouseEntered
        // TODO add your handling code here:
        setBackgroundBtn(inventoryBtn);
    }//GEN-LAST:event_inventoryBtnMouseEntered

    private void inventoryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtnMouseExited
        // TODO add your handling code here:
        resetBackgroundBtn(inventoryBtn);
    }//GEN-LAST:event_inventoryBtnMouseExited

    private void saleBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleBtn1MouseEntered
        // TODO add your handling code here:
        setBackgroundBtn(saleBtn1);
    }//GEN-LAST:event_saleBtn1MouseEntered

    private void saleBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleBtn1MouseExited
        // TODO add your handling code here:
        resetBackgroundBtn(saleBtn1);
    }//GEN-LAST:event_saleBtn1MouseExited

    private void productBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productBtn1MouseEntered
        // TODO add your handling code here:
        setBackgroundBtn(productBtn1);
    }//GEN-LAST:event_productBtn1MouseEntered

    private void productBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productBtn1MouseExited
        // TODO add your handling code here:
        resetBackgroundBtn(productBtn1);
    }//GEN-LAST:event_productBtn1MouseExited

    private void categoryBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryBtn1MouseEntered
        // TODO add your handling code here:
        setBackgroundBtn(categoryBtn1);
    }//GEN-LAST:event_categoryBtn1MouseEntered

    private void categoryBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryBtn1MouseExited
        // TODO add your handling code here:
        resetBackgroundBtn(categoryBtn1);
    }//GEN-LAST:event_categoryBtn1MouseExited

    private void customerBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerBtn1MouseEntered
        // TODO add your handling code here:
        setBackgroundBtn(customerBtn1);
    }//GEN-LAST:event_customerBtn1MouseEntered

    private void customerBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerBtn1MouseExited
        // TODO add your handling code here:
        resetBackgroundBtn(customerBtn1);
    }//GEN-LAST:event_customerBtn1MouseExited

    private void supplierBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierBtn1MouseEntered
        // TODO add your handling code here:
        setBackgroundBtn(supplierBtn1);
    }//GEN-LAST:event_supplierBtn1MouseEntered

    private void supplierBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierBtn1MouseExited
        // TODO add your handling code here:
        resetBackgroundBtn(supplierBtn1);
    }//GEN-LAST:event_supplierBtn1MouseExited

    private void userBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userBtn1MouseEntered
        // TODO add your handling code here:
        setBackgroundBtn(userBtn1);
    }//GEN-LAST:event_userBtn1MouseEntered

    private void userBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userBtn1MouseExited
        // TODO add your handling code here:
        resetBackgroundBtn(userBtn1);
    }//GEN-LAST:event_userBtn1MouseExited

    private void inventoryBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtn1MouseEntered
        // TODO add your handling code here:
        setBackgroundBtn(inventoryBtn1);
    }//GEN-LAST:event_inventoryBtn1MouseEntered

    private void inventoryBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtn1MouseExited
        // TODO add your handling code here:
        resetBackgroundBtn(inventoryBtn1);
    }//GEN-LAST:event_inventoryBtn1MouseExited

    private void categoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryBtnMouseClicked

    private void userBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userBtn1MouseClicked
        // TODO add your handling code here:
        userframe f=new userframe();
        f.setSize(1366,728);
        dispose();
        f.setVisible(true);
    }//GEN-LAST:event_userBtn1MouseClicked

    private void supplierBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierBtnMouseClicked
        // TODO add your handling code here:
        Supplier f=new Supplier();
        f.setSize(1366,728);
        dispose();
        f.setVisible(true);
    }//GEN-LAST:event_supplierBtnMouseClicked

    private void supplierBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierBtn1MouseClicked
        // TODO add your handling code here:
        Supplier f=new Supplier();
        f.setSize(1366,728);
        dispose();
        f.setVisible(true);
    }//GEN-LAST:event_supplierBtn1MouseClicked

    private void inventoryBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtn1MouseClicked
        Inventoryform f=new Inventoryform();
        f.setSize(1366,728);
        dispose();
        f.setVisible(true);
    }//GEN-LAST:event_inventoryBtn1MouseClicked

    private void inventoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtnMouseClicked
        dispose();
        Inventoryform f=new Inventoryform();
        f.setSize(1366,728);
        f.setVisible(true);
    }//GEN-LAST:event_inventoryBtnMouseClicked

    private void productBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productBtnMouseClicked
        // TODO add your handling code here:
        product f=new product(0);
        f.setSize(1366,728);
        dispose();
        f.setVisible(true);
    }//GEN-LAST:event_productBtnMouseClicked

    private void paymentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentBtnMouseClicked
        // TODO add your handling code here:
        payment f=new payment();
        f.setSize(1366,728);
        dispose();
        f.setVisible(true);
    }//GEN-LAST:event_paymentBtnMouseClicked

    private void paymentBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentBtnMouseEntered
        // TODO add your handling code here:
        setBackgroundBtn(paymentBtn);
    }//GEN-LAST:event_paymentBtnMouseEntered

    private void paymentBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentBtnMouseExited
        // TODO add your handling code here:
        resetBackgroundBtn(paymentBtn);
    }//GEN-LAST:event_paymentBtnMouseExited

    private void customerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerBtnMouseClicked
        customer f=new customer();
        f.setSize(1366,728);
        dispose();
        f.setVisible(true);
    }//GEN-LAST:event_customerBtnMouseClicked

    private void saleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleBtnMouseClicked
        // TODO add your handling code here:
        sales f=new sales();
        f.setSize(1366,728);
        dispose();
        f.setVisible(true);
    }//GEN-LAST:event_saleBtnMouseClicked

    private void saleBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleBtn1MouseClicked
        // TODO add your handling code here:
        sales f=new sales();
        f.setSize(1366,728);
        dispose();
        f.setVisible(true);
    }//GEN-LAST:event_saleBtn1MouseClicked

    private void productBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productBtn1MouseClicked
        // TODO add your handling code here:
        product f=new product(0);
        f.setSize(1366,728);
        dispose();
        f.setVisible(true);
    }//GEN-LAST:event_productBtn1MouseClicked

    private void customerBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerBtn1MouseClicked
        // TODO add your handling code here:
        customer f=new customer();
        f.setSize(1366,728);
        dispose();
        f.setVisible(true);
    }//GEN-LAST:event_customerBtn1MouseClicked
    public void resetBackgroundBtn(JPanel p){
       p.setBackground(new Color(64,43,100));
    }
    public void setBackgroundBtn(JPanel p){
        p.setBackground(new Color(85,85,118));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel categoryBtn;
    private javax.swing.JPanel categoryBtn1;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JPanel customerBtn;
    private javax.swing.JPanel customerBtn1;
    private javax.swing.JPanel dashboardBtn;
    private javax.swing.JPanel inventoryBtn;
    private javax.swing.JPanel inventoryBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel paymentBtn;
    private javax.swing.JPanel productBtn;
    private javax.swing.JPanel productBtn1;
    private javax.swing.JPanel saleBtn;
    private javax.swing.JPanel saleBtn1;
    private javax.swing.JPanel sidePane;
    private javax.swing.JPanel supplierBtn;
    private javax.swing.JPanel supplierBtn1;
    private javax.swing.JPanel userBtn1;
    // End of variables declaration//GEN-END:variables
}
